homepage:
  path: /{language}
  defaults:
    _controller: MentorshipMasterBundle:Master:index
    language: 'ru'
applicant_form:
  path: /form
  defaults:
    _controller: MentorshipMasterBundle:Master:form